"""Removed column 'age' from table 'patients'

Revision ID: 503594c1287c
Revises: 5413d2ea6b20
Create Date: 2024-07-17 11:44:10.322385+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '503594c1287c'
down_revision: Union[str, None] = '5413d2ea6b20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('age', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
