"""Set autoincrement to True for table Hospital, Doctor, and Patient

Revision ID: 6a42a6377fe3
Revises: 503594c1287c
Create Date: 2024-07-17 12:31:24.897476+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a42a6377fe3'
down_revision: Union[str, None] = '503594c1287c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
